/**
 * Demo data for Slice 2 — 12 sample customers across the three routes.
 * Replaced by real API data in a later slice.
 */

import type { CGCustomer, VanLoad } from './types';

export const initialVanLoad: VanLoad = {
  filledCans: 80,
  filledGallons: 60,
  emptyCansAboard: 0,
  emptyGallonsAboard: 0,
};

export const demoCustomers: CGCustomer[] = [
  // --- Hospital route ---
  {
    id: 'c-h1',
    name: 'DHQ Hospital — ICU Block',
    phone: '0300-1112233',
    address: 'DHQ Hospital, ICU Block, Timergara',
    route: 'hospital',
    usualCans: 4,
    usualGallons: 6,
    emptyCansHeld: 4,
    emptyGallonsHeld: 6,
    outstandingDebt: 0,
    pricePerCan: 250,
    pricePerGallon: 180,
    notes: 'Deliver before 9 AM. Ask for Sister Aisha.',
  },
  {
    id: 'c-h2',
    name: 'DHQ Hospital — OPD',
    phone: '0300-1112244',
    address: 'DHQ Hospital, OPD wing',
    route: 'hospital',
    usualCans: 3,
    usualGallons: 2,
    emptyCansHeld: 0,
    emptyGallonsHeld: 0,
    outstandingDebt: 0,
    pricePerCan: 250,
    pricePerGallon: 180,
  },
  {
    id: 'c-h3',
    name: 'Khan Medical Centre',
    phone: '0301-7788990',
    address: 'Hospital Road, near pharmacy',
    route: 'hospital',
    usualCans: 2,
    usualGallons: 3,
    emptyCansHeld: 2,
    emptyGallonsHeld: 0,
    outstandingDebt: 4500,
    pricePerCan: 270,
    pricePerGallon: 200,
    notes: 'Owes from previous month — chase payment.',
  },
  {
    id: 'c-h4',
    name: 'Saima Maternity Home',
    phone: '0312-4455667',
    address: 'Hospital Road, Block C',
    route: 'hospital',
    usualCans: 1,
    usualGallons: 2,
    emptyCansHeld: 1,
    emptyGallonsHeld: 0,
    outstandingDebt: 0,
    pricePerCan: 270,
    pricePerGallon: 200,
  },

  // --- Bypass route ---
  {
    id: 'c-b1',
    name: 'Al-Madina Restaurant',
    phone: '0344-5566778',
    address: 'Bypass Road, near fuel pump',
    route: 'bypass',
    usualCans: 5,
    usualGallons: 4,
    emptyCansHeld: 0,
    emptyGallonsHeld: 0,
    outstandingDebt: 0,
    pricePerCan: 260,
    pricePerGallon: 190,
  },
  {
    id: 'c-b2',
    name: 'Bypass Tyre Shop — Office',
    phone: '0345-9988776',
    address: 'Bypass Road, Tyre market',
    route: 'bypass',
    usualCans: 1,
    usualGallons: 1,
    emptyCansHeld: 1,
    emptyGallonsHeld: 1,
    outstandingDebt: 1200,
    pricePerCan: 260,
    pricePerGallon: 190,
  },
  {
    id: 'c-b3',
    name: 'Falcon Petrol Pump',
    phone: '0322-1010101',
    address: 'Bypass main road, opposite mosque',
    route: 'bypass',
    usualCans: 2,
    usualGallons: 1,
    emptyCansHeld: 0,
    emptyGallonsHeld: 0,
    outstandingDebt: 0,
    pricePerCan: 260,
    pricePerGallon: 190,
  },
  {
    id: 'c-b4',
    name: 'Hajji Karim Tea Stall',
    phone: '0331-2233445',
    address: 'Bypass turn, before bridge',
    route: 'bypass',
    usualCans: 1,
    usualGallons: 0,
    emptyCansHeld: 2,
    emptyGallonsHeld: 0,
    outstandingDebt: 0,
    pricePerCan: 260,
    pricePerGallon: 190,
    notes: 'Old man — be patient, sometimes pays slow.',
  },

  // --- Others route ---
  {
    id: 'c-o1',
    name: 'Government Boys School',
    phone: '0300-7654321',
    address: 'Main Bazaar, school street',
    route: 'others',
    usualCans: 2,
    usualGallons: 4,
    emptyCansHeld: 0,
    emptyGallonsHeld: 0,
    outstandingDebt: 0,
    pricePerCan: 240,
    pricePerGallon: 170,
    notes: 'Office hours only (8 AM – 2 PM).',
  },
  {
    id: 'c-o2',
    name: 'Hira Beauty Parlour',
    phone: '0335-8899001',
    address: 'Bazaar second floor',
    route: 'others',
    usualCans: 1,
    usualGallons: 0,
    emptyCansHeld: 1,
    emptyGallonsHeld: 0,
    outstandingDebt: 800,
    pricePerCan: 280,
    pricePerGallon: 210,
  },
  {
    id: 'c-o3',
    name: 'Rashid Auto Workshop',
    phone: '0310-7777888',
    address: 'Workshop street, near garage',
    route: 'others',
    usualCans: 1,
    usualGallons: 1,
    emptyCansHeld: 0,
    emptyGallonsHeld: 0,
    outstandingDebt: 0,
    pricePerCan: 270,
    pricePerGallon: 200,
  },
  {
    id: 'c-o4',
    name: 'Family — Akbar Khan',
    phone: '0303-2424242',
    address: 'House #14, Street 5',
    route: 'others',
    usualCans: 0,
    usualGallons: 1,
    emptyCansHeld: 0,
    emptyGallonsHeld: 1,
    outstandingDebt: 0,
    pricePerCan: 280,
    pricePerGallon: 220,
    notes: 'Domestic customer.',
  },
];
